# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

def getEvenFiboSum(_limit):
    firstNum, secondNum, sum = 0, 1, 0;
    while secondNum < _limit:
        #print(secondNum, end = ' ')
        firstNum, secondNum  = secondNum, firstNum + secondNum;
        if(secondNum > _limit):
            break;
        if(secondNum % 2 == 0):
            sum = sum + secondNum;
            
    return sum;

def main():
    limit = 4000000;
    print("Sum of even-valued terms: {}".format(getEvenFiboSum(limit)));

    
if __name__ == "__main__":
    main();